import { CountryModal } from "./Auth";

interface UserModal {
  id: number;
  email: string;
  firstname: string;
  lastname: string;
  avatar: string;
  provider_id: string;
  provider: string;
  stripe_id: string;
  gender: string;
  country_id: number;
  state_id: number;
  city_id: number;
  zipcode: string;
  dob: string;
  coordinate: string;
  phone: string;
  description: string;
  refer_id: string;
  reference: string;
  status: boolean;
  activated_at: string;
  deleted_at: string;
  created_at: string;
  updated_at: string;
  auto_renew: boolean;
  bank_token: string;
  card_token: string;
  stripe_token: string;
  stripe_payout: boolean;
  transfer_token: string;
  stripe_transfer: boolean;
  bank_name: string;
  bank_last4: string;
  individual_phone: string;
  individual_address_city: string;
  individual_address_line1: string;
  individual_address_state: string;
  individual_address_country: string;
  individual_postal_code: string;
  individual_ssn_last_4: number;
  company_name: string;
  company_phone: string;
  company_tax_id: string;
  company_address_city: string;
  company_address_line1: string;
  company_address_state: string;
  company_address_country: string;
  company_postal_code: string;
  card_name: string;
  card_last4: number;
  person_id: number;
  royalty_fee: number;
  is_temp: boolean;
  company_structure: string;
  customer_support_phone: string;
  os_type: string;
  os_version: string;
  user_language: string;
  first_login: boolean;
  is_deleted: boolean;
  franchise: Array<{ franchise_id: number; active: boolean }>;
  Franchise: Array<{ _Franchise: { id: number } }>;
  Country: CountryModal;
}

interface UsetInfoUpdateModal {
  city_id: number;
  country_id: number;
  email: string | null;
  firstname: string | null;
  lastname: string | null;
  state_id: number;
  zipcode: string;
  gender: string;
  dob: string;
  avatar: string | null;
  role: string;
  status: boolean;
  card_data_changed: boolean;
  bank_data_changed: boolean;
  individual_data_changed: boolean;
  franchise: Array<{ franchise_id: number; active: boolean }>;
  phone?: string;
}
export type { UserModal, UsetInfoUpdateModal };
